---
# Copyright 2014 John Bakker <me@johnbakker.name>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# github.com/webdevvie/openvpn-ansible-setup.git

- name: Set up ipv4 forwarding
  command: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Add default foward policy to ufw
  lineinfile: dest=/etc/default/ufw regexp='^#DEFAULT_FORWARD_POLICY' line='DEFAULT_FORWARD_POLICY="ACCEPT"' state=present

- name: enable ipv4 forwarding
  lineinfile: dest=/etc/ufw/sysctl.conf regexp='^#net.ipv4.ip_forward' line='net.ipv4.ip_forward=1' state=present

- name: install before.rules
  template: src=before.rules.j2 dest=/usr/share/ufw/before.rules

- name: Setup ufw to allow connections on port 22
  shell: ufw allow 22/tcp

- name: Setup ufw to allow connections on port for openvpn
  shell: ufw allow {{openvpn_port}}/tcp

- name: enable UFW
  shell: echo -e "y" | ufw enable

